concurrent = 1
check_interval = 0
log_level = "debug"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "docker docker-debian11-yocto-gma"
  url = "https://gitlab.linphone.org/"
  id = 141
  token = "my_token" # Put real token here
  token_obtained_at = 2022-12-16T12:56:18Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-yocto:kirkstone-qemux86_64"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/tmp/.X11-unix"]
    shm_size = 0
    network_mode = "host"
    cap_add = ["NET_ADMIN"]
    devices = ["/dev/snd", "/dev/kvm"]
